export * from './Home/Home'
export * from './Detail/Detail'
export * from './Sneakers/Sneakers'
export * from './Authentication/Login'
export * from './Authentication/Register'
export * from './About/About'